// src/app/shared/components/nav/nav.component.ts
import { Component } from '@angular/core';
import { RouterLink, RouterLinkActive } from '@angular/router';
@Component({
  selector: 'app-nav',
  standalone: true,
  imports: [RouterLink, RouterLinkActive],
  templateUrl: './nav.component.html',
  styleUrl: './nav.component.css',
})
export class NavComponent {}

<nav>
  <ul class="flex items-center gap-5">
    <li>
      <a routerLink="" routerLinkActive="active">
        <img src="assets/icon-nav-home.svg" alt="icon home" />
      </a>
    </li>
    <li>
      <a routerLink="/movies" routerLinkActive="active">
        <img src="assets/icon-nav-movies.svg" alt="icon movie" />
      </a>
    </li>
    <li>
      <a routerLink="/series" routerLinkActive="active">
        <img src="assets/icon-nav-tv-series.svg" alt="icon series" />
      </a>
    </li>
    <li>
      <a routerLink="/bookmark" routerLinkActive="active">
        <img src="assets/icon-nav-bookmark.svg" alt="icon bookmark" />
      </a>
    </li>
  </ul>
</nav>

// app/components/Nav.tsx
'use client';
import Image from 'next/image';
import Logo from '../assets/logo.svg';
import Movies from '../assets/icon-nav-movies.svg';
import TvSeries from '../assets/icon-nav-tv-series.svg';
import Bookmarked from '../assets/icon-nav-bookmark.svg';
import Home from '../assets/icon-nav-home.svg';
import Avatar from '../assets/image-avatar.png';
import Link from 'next/link';

export default function Nav() {
  return (
    <div className=" bg-blue_1  h-[10vh] flex items-center justify-between px-3 sm:m-5 sm:rounded-md">
      <div>
        <Image
          src={Logo}
          alt="logo"
          width={25}
          height={20}
          className="sm:w-[32px] sm:h-[25px]"
        />
      </div>
      <div className="flex items-center gap-5">
        <Link href="/">
          <Image
            src={Home}
            width={25}
            height={20}
            className="sm:w-[32px] sm:h-[25px]"
            alt="home"
          />
        </Link>
        <Link href="/movies">
          <Image
            src={Movies}
            width={25}
            height={20}
            className="sm:w-[32px] sm:h-[25px]"
            alt="home"
          />
        </Link>
        <Link href="/tvseries">
          <Image
            src={TvSeries}
            width={25}
            height={20}
            className="sm:w-[32px] sm:h-[25px]"
            alt="home"
          />
        </Link>
        <Link href="/bookmarked">
          <Image
            src={Bookmarked}
            width={25}
            height={20}
            className="sm:w-[32px] sm:h-[25px]"
            alt="home"
          />
        </Link>
      </div>
      <div>
        <Image
          src={Avatar}
          alt="avatar"
          width={25}
          height={25}
          className="sm:w-[32px] sm:h-[25px]"
          style={{
            border: '1px solid white',
            borderRadius: '50%',
            objectFit: 'cover',
          }}
        />
      </div>
    </div>
  );
}
